<div class="company_table d-flex align-items-start">
    <div class="tab_list_box tab_btn nav flex-column nav-pills " id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'business-overview') active @endif" id="v-pills-home-tab" data-bs-toggle="pill" data-bs-target="#v-pills-home" type="button" onclick="  window.location.href = '{{ route('business_overview.index') }}'"   role="tab" aria-controls="v-pills-home" aria-selected="true"> <img class="simple_one max-width-10" src="{{asset('assets/images/managericons/business_overview.svg')}}"><img class="hover_one  max-width-10" src="{{asset('assets/images/managericons/business_overview_hover.svg')}}">Business Overview</button>
        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'merchandiser-timeSheet') active @endif" id="v-pills-profile-tab" data-bs-toggle="pill" data-bs-target="#v-pills-profile" type="button" onclick=" window.location.href = '{{ route('merchandiser_time_sheet.index') }}'" role="tab" aria-controls="v-pills-profile" aria-selected="false"><img class="simple_one max-width-10" src="{{asset('assets/images/managericons/merchandiser_timesheet.svg')}}"><img class="hover_one  max-width-10" src="{{asset('assets/images/managericons/merchandiser_timesheet_hover.svg')}}">Merchandiser Time Sheet</button>
        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'stock-count-by-store') active @endif" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" onclick=" window.location.href = '{{ route('stock_count_by_store.index') }}'"  role="tab" aria-controls="v-pills-settings" aria-selected="false"><img class="simple_one max-width-10" src="{{asset('assets/images/managericons/stock_count.svg')}}"><img class="hover_one  max-width-10" src="{{asset('assets/images/managericons/stock_count_hover.svg')}}">Stock Count by Store</button>
        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'out-of-stock') active @endif" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" onclick=" window.location.href = '{{ route('out_of_stock.index') }}'"  role="tab" aria-controls="v-pills-settings" aria-selected="false"><img class="simple_one max-width-10" src="{{asset('assets/images/managericons/out_of_stock.svg')}}"><img class="hover_one  max-width-10" src="{{asset('assets/images/managericons/out_of_stock_hover.svg')}}">Out of Stock</button>
        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'price-audit-data') active @endif" id="v-pills-messages-tab" data-bs-toggle="pill" data-bs-target="#v-pills-messages" type="button" onclick=" window.location.href = '{{ route('price_audit.index') }}'" role="tab" aria-controls="v-pills-messages" aria-selected="false"><img class="simple_one max-width-10" src="{{asset('assets/images/managericons/price_audit.svg')}}"><img class="hover_one  max-width-10" src="{{asset('assets/images/managericons/price_audit_hover.svg')}}">Price Audit</button>
        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'planogram-compliance-tracker') active @endif" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" onclick=" window.location.href = '{{ route('planogram_compliance_tracker.index') }}'"  role="tab" aria-controls="v-pills-settings" aria-selected="false"><img class="simple_one max-width-10" src="{{asset('assets/images/managericons/planogram_complaince.svg')}}"><img class="hover_one  max-width-10" src="{{asset('assets/images/managericons/planogram_complaince_hover.svg')}}">Planogram Compliance Tracker</button>
        {{-- <button class="nav-link @if($pageConfigs['pageSidebar'] == 'sellin-vs-sellout-data') active @endif" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" onclick=" window.location.href = '{{ route('sellin_vs_sellout_data.index') }}'"  role="tab" aria-controls="v-pills-settings" aria-selected="false"><img class="simple_one max-width-10" src="{{asset('assets/images/managericons/business_overview.svg')}}"><img class="hover_one  max-width-10" src="{{asset('assets/images/managericons/business_overview_hover.svg')}}">Sell in vs Sell out Data</button> --}}
        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'product-expiry-tracker') active @endif" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" onclick=" window.location.href = '{{ route('product_expiry_tracker.index') }}'"  role="tab" aria-controls="v-pills-settings" aria-selected="false"><img class="simple_one max-width-10" src="{{asset('assets/images/managericons/product_expiry.svg')}}"><img class="hover_one  max-width-10" src="{{asset('assets/images/managericons/product_expiry_hover.svg')}}">Product Expiry or Damaged Tracker</button>
        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'marketing-activity') active @endif" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" onclick=" window.location.href = '{{ route('marketing_activity.index') }}'"  role="tab" aria-controls="v-pills-settings" aria-selected="false"><img class="simple_one max-width-10" src="{{asset('assets/images/managericons/marketing_activity.svg')}}"><img class="hover_one  max-width-10" src="{{asset('assets/images/managericons/marketing_activity_hover.svg')}}">Marketing Activity</button>
        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'opportunities') active @endif" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" onclick=" window.location.href = '{{ route('web_opportunity.index') }}'"  role="tab" aria-controls="v-pills-settings" aria-selected="false"><img class="simple_one max-width-10" src="{{asset('assets/images/managericons/opportunities.svg')}}"><img class="hover_one  max-width-10" src="{{asset('assets/images/managericons/opportunities_hover.svg')}}">Opportunity / Threat</button>
        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'notification') active @endif" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" onclick=" window.location.href = '{{ route('web_notification.index') }}'"  role="tab" aria-controls="v-pills-settings" aria-selected="false"><img class="simple_one max-width-10" src="{{asset('assets/images/managericons/notification.svg')}}"><img class="hover_one  max-width-10" src="{{asset('assets/images/managericons/notification_hover.svg')}}">Notification</button>
    </div>
</div>