<div class="company_table d-flex align-items-start sidebar full-width" id="sidebar">
    <div class="tab_list_box tab_btn nav flex-column nav-pills " id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <!-- <button class="nav-link @if($pageConfigs['pageSidebar'] == 'company') active @endif" id="v-pills-home-tab" data-bs-toggle="pill" data-bs-target="#v-pills-home" type="button" onclick=" window.location.href = '{{ route('company.index') }}'" role="tab" aria-controls="v-pills-home" aria-selected="true"><img class="simple_one max-width-10" src="{{asset('assets/images/company.svg')}}"><img class="hover_one  max-width-10" src="{{asset('assets/images/company_hover.svg')}}"> Company</button>
        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'user') active @endif" id="v-pills-profile-tab" data-bs-toggle="pill" data-bs-target="#v-pills-profile" type="button" onclick=" window.location.href = '{{ route('user.index') }}' " role="tab" aria-controls="v-pills-profile" aria-selected="false"><img class="simple_one  max-width-10" src="{{asset('assets/images/user.svg')}}"><img class="hover_one max-width-10" src="{{asset('assets/images/user_hover.svg')}}">User</button>
        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'store') active @endif" id="v-pills-messages-tab" data-bs-toggle="pill" data-bs-target="#v-pills-messages" type="button" onclick=" window.location.href = '{{ route('store.index') }}' " role="tab" aria-controls="v-pills-messages" aria-selected="false"><img class="simple_one max-width-10" src="{{asset('assets/images/store.svg')}}"><img class="hover_one  max-width-10" style="width:40px;" src="{{asset('assets/images/store_hover.svg')}}">Store</button>
        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'category') active @endif" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" onclick=" window.location.href = '{{ route('category.index') }}' " role="tab" aria-controls="v-pills-settings" aria-selected="false"><img class="simple_one max-width-10" src="{{asset('assets/images/category.svg')}}"><img class="hover_one max-width-10" style="width:40px;"x src="{{asset('assets/images/category_hover.svg')}}">Category</button>
        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'product') active @endif" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" onclick=" window.location.href = '{{ route('product.index') }}' " role="tab" aria-controls="v-pills-settings" aria-selected="false"><img class="simple_one max-width-10" src="{{asset('assets/images/product.svg')}}"><img class="hover_one max-width-10" style="width:40px;"x src="{{asset('assets/images/product_hover.svg')}}">Product</button>
 -->



        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'dispatch') active @endif" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" onclick=" window.location.href = '{{ route('dispatch.index') }}' " role="tab" aria-controls="v-pills-settings" aria-selected="false"><img class="simple_one max-width-10" src="{{asset('assets/images/product.svg')}}"><img class="hover_one max-width-10" style="width:40px;"x src="{{asset('assets/images/product_hover.svg')}}">Dispatch</button>
        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'user') active @endif" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" onclick=" window.location.href = '{{ route('appuser.index') }}' " role="tab" aria-controls="v-pills-settings" aria-selected="false"><img class="simple_one max-width-10" src="{{asset('assets/images/product.svg')}}"><img class="hover_one max-width-10" style="width:40px;"x src="{{asset('assets/images/product_hover.svg')}}">App User</button>
        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'driver') active @endif" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" onclick=" window.location.href = '{{ route('driver.index') }}' " role="tab" aria-controls="v-pills-settings" aria-selected="false"><img class="simple_one max-width-10" src="{{asset('assets/images/product.svg')}}"><img class="hover_one max-width-10" style="width:40px;"x src="{{asset('assets/images/product_hover.svg')}}">Driver</button>
        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'job_history') active @endif" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" onclick=" window.location.href = '{{ route('JobHistory.index') }}' " role="tab" aria-controls="v-pills-settings" aria-selected="false"><img class="simple_one max-width-10" src="{{asset('assets/images/product.svg')}}"><img class="hover_one max-width-10" style="width:40px;"x src="{{asset('assets/images/product_hover.svg')}}">Job History</button>
        <button class="nav-link @if($pageConfigs['pageSidebar'] == 'setting') active @endif" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" onclick=" window.location.href = '{{ route('setting.index') }}' " role="tab" aria-controls="v-pills-settings" aria-selected="false"><img class="simple_one max-width-10" src="{{asset('assets/images/product.svg')}}"><img class="hover_one max-width-10" style="width:40px;"x src="{{asset('assets/images/product_hover.svg')}}">Setting</button>
    </div>
</div>
